[package]
name = "ironsmith-model"
version = "0.1.0"
edition = "2021"

[dependencies]
ironsmith-parser = { path = "../ironsmith-parser" }
serde = { version = "1", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
